// Content fragments: renderEmailHtml adds the account's actual logo/footer.
const shop = 'https://veilpuff.com/shop';
const notes = 'Original — jasmine, hinoki and creamy vanilla.\nCitron Lumineaux — bergamot, neroli and cedar.\nViolette Ambrée — pear, soft florals and warm amber.';
const entry = 'Veil is powdered fragrance. Featherlight. Swept onto skin with a soft puff. Noticed by those who lean in close.';
const invitation = 'Your first order is 15% less with code VEIL15. Enter it at checkout.';
export const welcomeContent = {
  welcome: { subject: 'A softer way to wear scent', preview: 'Powdered fragrance, worn close. Your 15% welcome code is inside.', heading: 'Your first veil of fragrance.', body: ['Welcome to Veil.', 'For the woman who wants to be remembered by her scent, not announced by it.', entry, 'Three compositions, three ways to begin.', notes, 'Choose the notes that feel like you.', invitation, 'Press. Sweep. Let it stay close.'], cta: 'Find my scent' },
  survey: { subject: 'May we help you choose?', preview: 'A small question. An answer made for you.', heading: 'What gave you pause?', body: ['Choosing fragrance online can feel personal.', 'Perhaps the notes are not quite clear. Perhaps powder feels unfamiliar. Or perhaps life simply carried on.', 'We would rather help than hurry you. What gave you pause?'], survey: true },
  scent4: { subject: 'Three ways to find your scent', preview: 'Warm flowers. Bright citrus. Soft fruit and amber.', heading: 'The notes you already love.', body: ['A scent description is only a beginning. But familiar notes can make the first choice feel easier.', 'Original is floral and warm. Jasmine unfolds over grounding hinoki and creamy vanilla.', 'Citron Lumineaux is bright and woody. Bergamot and neroli settle into cedar and white woods.', 'Violette Ambrée is delicate and romantic. Pear and plum open into lily of the valley and violet, then amber and soft woods.', 'Which one sounds like something you would reach for? Begin there.'], cta: 'Explore the three scents' },
  scent7: { subject: 'When one note feels familiar', preview: 'Floral warmth, luminous citrus, or fruit and amber.', heading: 'When one note feels familiar.', body: ['Think of the fragrance you reach for most.', 'If you love flowers and vanilla, meet Original.\nIf you prefer citrus and woods, meet Citron Lumineaux.\nIf fruit, soft flowers and amber draw you in, meet Violette Ambrée.', 'There is no correct choice. Only the one you want to wear close.'], cta: 'Find my scent' },
  powder4: { subject: 'Pressed in. Not sprayed on.', preview: 'A featherlight powder. A close-to-skin scent. Three soft motions.', heading: 'Pressed in. Not sprayed on.', body: ['It is fragrance, in a different form.', 'Press the puff into the powder.\nSweep a light veil onto clean skin—collarbones, shoulders, or the backs of the knees.\nLet the scent stay close.', 'Wear it alone, or layer it with a perfume you already love.', 'The formula is vegan, cruelty-free and talc-free. The feeling is soft. The fragrance is yours to choose.'], cta: 'Discover perfume powder', url: 'https://veilpuff.com/product/original' },
  powder7: { subject: 'A veil, not a coat', preview: 'A light sweep is a lovely place to begin.', heading: 'A veil, not a coat.', body: ['The first sweep need not be complicated.', 'Press the puff lightly into the powder. Sweep onto clean skin. Begin with a little, rather than a heavy layer.', 'Original brings jasmine, vanilla and warm woods. Citron Lumineaux brings bright citrus. Violette Ambrée brings fruit, flowers and amber.', 'The ritual is the same. The scent is personal.'], cta: 'Choose the scent to wear' },
  price4: { subject: 'Begin with one jar', preview: 'One 4oz fragrance. Your original 15% invitation.', heading: 'Begin with one jar.', body: ['You do not need the whole collection to begin.', 'Choose one 4oz jar—Original, Citron Lumineaux or Violette Ambrée. Each is $45 and comes with the Veil Luxury Puff.', 'Use your eligible VEIL15 code for 15% off at checkout. Shipping and any tax are shown separately.', 'One scent. A soft sweep. A moment that belongs to you.'], cta: 'Choose one jar' },
  price7: { subject: 'The puff is already included', preview: 'The fragrance and its soft puff. Nothing more to add.', heading: 'The puff is already included.', body: ['A first jar is enough.', 'Every 4oz scent comes with the Veil Luxury Puff. There is no need to add another puff to begin wearing it.', 'Choose the notes you love. Leave the rest for another day.', 'If now is not the right moment, there is no need to turn one jar into a larger order.'], cta: 'See the 4oz scents' },
  timing4: { subject: 'Whenever you have a moment', preview: 'The collection is here to revisit. No hurry from us.', heading: 'Whenever you have a moment.', body: ['Life carries on. A new fragrance can wait its turn.', 'When you have a moment, meet the collection again. Original is floral and warm. Citron Lumineaux is bright and woody. Violette Ambrée is fruit, flowers and amber.', 'Nothing has been reserved. No order has been placed. Just an easy way back, if you want it.'], cta: 'Return to the collection' },
  timing7: { subject: 'For the next time you get ready', preview: 'A softer finishing touch, whenever the moment feels right.', heading: 'For the next time you get ready.', body: ['Imagine the last small moment before you leave.', 'A light sweep across the collarbones. The scent you chose, close to your skin.', 'Not to announce yourself. Just to feel like yourself.', 'When the timing feels right, begin with one jar.'], cta: 'Find my fragrance' },
  day14: { subject: 'The scent before you leave', preview: 'A small finishing touch. A fragrance that stays close.', heading: 'The scent before you leave.', body: ['Some finishing touches are not meant to be seen.', 'After the bath. Before the dress. A soft sweep of fragrance, just for you.', 'Veil is powdered perfume, made in Los Angeles. Vegan, cruelty-free and talc-free. Worn alone, or layered with a scent you already love.', notes, 'Choose the one you want beside you through the day.'], cta: 'Find my everyday scent' },
  day30: { subject: 'Shall we leave it here?', preview: 'The last note in this welcome series. A simple way back, if you want it.', heading: 'Shall we leave it here?', body: ['We would rather be welcome than simply present.', 'If you still want to meet Veil, the collection is here. Three powdered fragrances, each worn close to skin.', 'Your first-order code is VEIL15, for 15% off while eligible. Enter it at checkout.', 'If now is not your moment, we will leave this welcome series here. You may still receive the occasional collection letter. If you would rather receive no marketing emails, you can unsubscribe below.', 'Thank you for spending a little time with us.'], cta: 'Revisit the collection' },
};
export function escapeHtml(value) {
  return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}
export function contentHtml(key, answerUrls = {}) {
  const item = welcomeContent[key];
  if (!item) throw new Error('Unknown welcome step');
  const p = (text) => `<p style="font-family:'Hanken Grotesk',Arial,sans-serif;font-size:17px;line-height:1.65;color:#16140F;margin:0 0 22px;">${escapeHtml(text).replace(/\n/g, '<br>')}</p>`;
  const button = (label, url) => `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:16px 0;"><tr><td bgcolor="#16140F" style="mso-padding-alt:16px 24px;"><a href="${escapeHtml(url)}" style="display:inline-block;padding:16px 24px;color:#FCFBF7;text-decoration:none;font-family:Arial,sans-serif;font-size:15px;">${escapeHtml(label)}</a></td></tr></table>`;
  const choices = [['scent', 'Not sure which scent'], ['powder', 'Not sure powder suits me'], ['price', 'Price'], ['timing', 'Haven’t gotten to it']];
  const actions = item.survey ? choices.map(([a, label]) => {
    if (!/^https:\/\//.test(answerUrls[a] || '')) throw new Error('Answer link missing');
    return button(label, answerUrls[a]);
  }).join('') : button(item.cta, item.url || shop);
  return `<div style="display:none;max-height:0;overflow:hidden;opacity:0;mso-hide:all;">${escapeHtml(item.preview)}</div><div style="background:#FCFBF7;padding:24px;"><h1 style="font-family:'Fraunces',Georgia,serif;font-size:36px;font-weight:normal;color:#16140F;">${escapeHtml(item.heading)}</h1>${item.body.map(p).join('')}${actions}</div>`;
}
